=== faucetsdn/daq/schemas/udmi/config.json
{
  "title": "Device Config Schema",
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "required": [
    "timestamp",
    "version",
    "system"
  ],
  "properties": {
    "timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "version": {
      "enum": [
        1
      ]
    },
    "system": {
      "$ref": "file:config_system.json#"
    },
    "pointset": {
      "$ref": "file:config_pointset.json#"
    }
  }
}

=== faucetsdn/daq/schemas/udmi/config.tests/smartprimus.json
{
  "version": 1,
  "timestamp": "2019-01-17T14:02:29.364Z",
  "system": {
  },
  "pointset": {
    "sample_rate_sec": 2,
    "points": {
      "space_temperature_sensor": {
      },
      "fan_run_status": {
        "force_value": true
      },
      "fan_run_enable": {
        "force_value": false
      },
      "chilled_water_valve_percentage_command": {
      }
    }
  }
}

=== faucetsdn/daq/schemas/udmi/config.tests/fcu.json
{
  "version": 1,
  "timestamp": "2019-01-17T14:02:29.364Z",
  "system": {
    "max_update_ms": 50000,
    "min_loglevel": 500
  },
  "pointset": {
    "points": {
      "space_temperature_sensor": {
      },
      "fan_run_status": {
        "fix_value": true
      },
      "fan_run_enable": {
        "fix_value": false
      },
       "chilled_water_valve_percentage_command": {
        "min_update_ms": 1000
      }
    }
  }
}

=== faucetsdn/daq/schemas/udmi/metadata.tests/example.json
{
  "version": 1,
  "timestamp": "2018-08-26T21:39:29.364Z",
  "system": {
    "location": {
      "site": "US-SFO-XYY",
      "section": "NW-2F",
      "position": {
        "x": 10,
        "y": 20
      }
    },
    "physical_tag": {
      "asset": {
        "guid": "bim://04aEp5ymD_$u5IxhJN2aGi",
        "site": "US-SFO-XYY",
        "suffix": "extention11-optional",
        "name": "AHU-1"
      }
    }
  },
  "pointset": {
    "points": {
      "return_air_temperature_sensor": {
        "units": "Degrees-Celsius"
      }
    }
  }
}
